title: 我的博客
description: WordPress 同步过来的文章
# 项目托管地址
baseurl: "/sky"        # 必须和仓库名一致
theme: minima          # 使用默认主题

# 插件列表（使用分页 v2）
plugins:
  - jekyll-paginate-v2

# paginate-v2 全局配置
pagination:
  enabled: true
  per_page: 30               # 每页显示文章数
  permalink: '/page:num'     # 分页路径
  title: ':title - 第:num页' # SEO 友好标题
  sort_field: 'date'         # 按日期排序
  sort_reverse: true         # 最新文章在前
  trail:                     # 分页导航显示范围
    before: 2
    after: 2

# Markdown & 语法高亮
markdown: kramdown
highlighter: rouge

# 构建排除项
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# 可选：默认分页首页模板
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
