title: 我的博客
description: WordPress 同步过来的文章
# 如果你的项目托管在 https://github.com/719729765/sky/
baseurl: "/sky"  # 必须和仓库名一致
theme: minima    # 使用默认主题
paginate: 30     # 每页显示 30 篇文章
paginate_path: "/page:num"  # 分页路径
plugins:
  - jekyll-paginate          # 确保分页插件启用
